### ISSUE TITLE
Docs>Impact page: Image does not match text description

### ISSUE THREAD

**Issue by ylevtov** [mixpanel/docs-legacy#250]
https://github.com/mixpanel/docs/blob/4dc938492b2d01d41ac7df45f24f2c74c7dd3075/pages/docs/analysis/advanced/impact.md?plain=1#L31

**Comment by ylevtov** [comment]
In fact I'm not sure many of the images on this page match the text...

**Comment by ranic** [comment]
Thanks for catching, turns out there were several of these due to using overlapping path names for images. Luckily was easy to grep for this pattern and fix all of them, over the following commits:
 https://github.com/mixpanel/docs/commit/bebeec85685a75dc4cae62aa09aa2487b5db6793

https://github.com/mixpanel/docs/commit/5242e7e4e32878bf637d16e5bd7db9b55a50fe40

https://github.com/mixpanel/docs/commit/bb5d028df27a32222dcc76a4344b8e9e1d1c2d80

https://github.com/mixpanel/docs/commit/ae2717e64136de460bf57b0aca0beb1033156d0a

https://github.com/mixpanel/docs/commit/a9157db41191e84dd3c8f611d69d3604f4a490d4
